### ISSUE TITLE
/research deeper doesn't know a collection name has changed

### ISSUE THREAD

**Issue by asehmi** [reasonmethis/docdocgo-core#16]
After using `/research some topic` a collection is created with a proposed name, say "X". If you run `/research deeper` in "X" the "X" collection is enriched (as far as I understand). However, if you rename the collection name to "Y", say, and run `/research deeper` again from "Y" the "X" collection is created anew. I was expecting it to enrich "Y" not create a new "X". So `/research deeper` knew the topic it had to research but not the new collection name it had to use. Is there a collection name in the db that isn't being picked up in this command?

**Comment by reasonmethis** [comment]
Great catch! I just pushed a bug fix for this issue.
