### ISSUE TITLE
Saving output

### ISSUE THREAD

**Issue by asehmi** [reasonmethis/docdocgo-core#17]
Would it make sense to write DDG results console output (not errors) into a file in addition to the console. This should be easy to do with a custom logger. The issue might be to have per user result logs. Perhaps users could specify their log file in the sidebar so you can add a download button in the sidebar too.

Currently, I'm selecting and copying console markdown output, which is feasible only because I'm using DDG locally.

Do you have plans to save/download results?

**Comment by reasonmethis** [comment]
I need to implement a more serious logging system in place of the amateurish random print statement. It might be a while till I get to it. What kin of console output do you copy? Is it something that is not output by the Streamlit UI?

**Comment by asehmi** [comment]
Yes, I am copying and pasting the Streamlit console output (markdown). This requirement is for cloud version and those non techs who won't look at the console/terminal.

**Comment by reasonmethis** [comment]
So are we talking about the Markdown rendered by the Streamlit UI or the logs in the Python console (which the non-techs don't care about)?

**Comment by asehmi** [comment]
Logs in console. I cut and paste them into .md files then convert to PDF/etc. with pandoc & wkhtmltopdf. Actually, a common workflow I do is lots of research/cut/paste/append cycles and ingest all of it into DDG (plain text or Word, not PDF as above process generates image PDFs).

**Comment by reasonmethis** [comment]
Do the logs in the console contain something important for your use case that is not present in the Streamlit UI output, or is this just to get the Markdown and not just plain text.

In other words, would it work if the UI had an option to export the whole conversation in Markdown format and/or have a copy button next to each response (like ChatGPT does)?

**Comment by asehmi** [comment]
A markdown export would be great. Copying the Streamlit text is not ideal.

**Comment by reasonmethis** [comment]
Done and done :grin:
