### ISSUE TITLE
FastAPI unable to resolve user_id in /chat endpoint

### ISSUE THREAD

**Issue by asehmi** [reasonmethis/docdocgo-core#21]
In case a user doesn't enter their OpenAI API key in `https://docdocgo-nextjs-basic.vercel.app/` (or include it in the API post body), relying instead on the `.env` file `DEFAULT_OPENAI_API_KEY` key in the running FastAPI server, you will not be able to resolve the `user_id`. This results in the user's collections being invisible. I fixed the problem by changing lines 302, 303 like this:

```python
        openai_api_key: str = data.openai_api_key or DEFAULT_OPENAI_API_KEY
        user_id: str | None = get_short_user_id(openai_api_key)
```

**Comment by reasonmethis** [comment]
The general principle I have adopted is that DEFAULT_OPENAI_API_KEY is meant to be a community key (costs are paid by the person who hosts the backend, collections are public). I can make it so BYPASS_SETTINGS_RESTRICTIONS being set changes that default behavior in the API, just as it does in the Streamlit app.

**Comment by asehmi** [comment]
I think you just need to make the change I proposed. I don't think it'll change your intent, unless you don't want the community key (DEFAULT_OPENAI_API_KEY) to be used via the API. Maybe setting BYPASS_SETTINGS_RESTRICTIONS as you suggest is better.
