### ISSUE TITLE
Collection name prefix search not working

### ISSUE THREAD

**Issue by asehmi** [reasonmethis/docdocgo-core#24]
I found the prefix search `/db list blah*` doesn't work since `collection.name` is the full name of the collection, not its as-shown name. I fixed this by replacing `dbmanager.py#L358-L367` with the following so the as-shown name is used with the `filter_func` lambda.

```python
    for i, collection in enumerate(collections[idx_start:], start=idx_start):
        coll_name_as_shown = get_user_facing_collection_name(user_id, collection.name)
        if filter_str and not filter_func(coll_name_as_shown):
            continue
        if len(entries) >= COLLECTION_GROUP_SIZE:
            are_there_more = True  # there are more matching collections than we'll show
            break  # break without adding the current collection

        dt = get_time_str((collection.metadata or {}).get("updated_at"))
        entries.append(f"| {i+1} | `{coll_name_as_shown[:40]}` | {dt} |")
```

https://github.com/reasonmethis/docdocgo-core/blob/ae9315b2d5f95f8d6698176867c7cf958da80c42/agents/dbmanager.py#L358-L367

**Comment by reasonmethis** [comment]
Great catch! I have updated the code with your fix. :rocket:
