### ISSUE TITLE
Add `/summarize` command to HELP_MESSAGE

### ISSUE THREAD

**Issue by asehmi** [reasonmethis/docdocgo-core#4]
Small omission, the following is missing from `/help` command:

"- `/summarize https://some.url.com`: retrieve a URL, summarize and ingest into a collection!"

**Comment by reasonmethis** [comment]
Hey there, I tested this by running "/help" and here's an excerpt from the full reply:

```
How to use me
You can enter your messages with or without a prefix. Different prefixes activate my different response modes. Think of them like different subagents, each with a different job. The default mode is /docs.

Here's what each prefix does. Most important ones:

/research <your query>: perform "infinite" Internet research, ingesting websites into a collection
/docs <your query>: chat about your currently selected doc collection (or a general topic)
/ingest: upload your documents and ingest them into a collection
/ingest https://some.url.com: retrieve a URL and ingest into a collection
/summarize https://some.url.com: retrieve a URL, summarize and ingest into a collection
/db: manage your doc collections (select, rename, etc.)
/help <your query>: get help with using DocDocGo
```

So at least in the current version the `/summarize` command is mentioned. Let me know if you are talking about a different scenario. 

Also, I just added a new feature: you can now run `/help <your question>` to get help without having to first switch to the default collection.

**Comment by asehmi** [comment]
Weird it works now... maybe the code didn't sync as I expected because I had made some changes (to the write_slowly function so it would write faster, word-by-word not char-by-char) and to the font size and central column width (to suit my very wide hires screen).
