### ISSUE TITLE
Avoid wiping existing DBs on git pull

### ISSUE THREAD

**Issue by asehmi** [reasonmethis/docdocgo-core#5]
Hi there - I am planning to get into your app over the coming weeks. Can you please explain how to take advantage of: 

```
COLLECTON_NAME_FOR_INGESTED_DOCS="" # collection name for the docs you want to ingest
DOCS_TO_INGEST_DIR_OR_FILE="" # path to directory or single file with your docs to ingest
```

I'd like to be assured that when I a pull a new release that I will still have access to my existing doc collections, please.

Thanks.

**Comment by reasonmethis** [comment]
Sure, the easiest way is to set:
```
VECTORDB_DIR="some-custom-dir-name-outside-of-project-dir/" # directory of your doc database
```

That way you don't have to worry about the `chroma/` directory being freshly pulled from this repo. To make sure your custom directory contains the default collection `docdocgo-documentation`, which is what the `chroma/` directory contains initially, you should be able to simply copy the contents of `chroma/` to your chosen custom directory. 

As an alternative way to handle the issue of the default collection, you can create your own version of the default collection by ingesting the README, along with any other files you wish to be included. To make the resulting collection the default collection, use the command `/db rename --default <admin pwd you set>`, where the admin password is the value you assigned to the `BYPASS_SETTINGS_RESTRICTIONS_PASSWORD` environment variable.

The environment variables you mentioned in your post are only useful if you want to ingest documents not using the Streamlit UI, but in console mode. If you are using the Streamlit UI, there is not much advantage in ingesting via the console mode.

Thank you for flagging this issue. I have been so focused on the multi-user, cloud db use case that I haven't done enough due diligence to iron out the wrinkles in the local db use case.

**Comment by asehmi** [comment]
Thanks for advice.
